### ISSUE TITLE
Permission Dialog Not Displayed and Communication Fails on Google Pixel 7 Running Android 14

### ISSUE THREAD

**Issue by HristoPetkov94** [farellsujanto/flutter_serial_communication#19]
When attempting to establish communication on a Google Pixel 7 running Android 14, the permission dialog does not appear, resulting in a failure to initiate communication. This issue prevents the app from functioning correctly on devices with this configuration.

**Comment by DominikStarke** [comment]
Can you please test my pull request? It adresses these Issues with Android 14:
https://github.com/farellsujanto/flutter_serial_communication/pull/17

**Comment by HristoPetkov94** [comment]
yes, it is working. Thanks

**Comment by HristoPetkov94** [comment]
I'm looking forward to seeing your changes merged into the main branch.

**Comment by farellsujanto** [comment]
released v0.2.7 with the fix, closing this issue
