### ISSUE TITLE
Not getting red message to the arduino

### ISSUE THREAD

**Issue by Geetanshu24** [farellsujanto/flutter_serial_communication#5]
I am using this metho
  _flutterSerialCommunicationPlugin.getSerialMessageListener().receiveBroadcastStream().listen((event) {
     debugPrint("Recieved data is: $event");
     setState(() {
     });
    });

**Comment by farellsujanto** [comment]
Are you already run the connection code?

**Comment by Geetanshu24** [comment]
yes , and the connection is already done, also send message is performing but read message is not performing

**Comment by farellsujanto** [comment]
Can you tell me what arduino are you using?

**Comment by Geetanshu24** [comment]
UNO8

**Comment by enfelipesiqueira** [comment]
> I am using this metho _flutterSerialCommunicationPlugin.getSerialMessageListener().receiveBroadcastStream().listen((event) { debugPrint("Recieved data is: $event"); setState(() { }); });

I had the same issue. Try using event.toString() and the compiled version. Maybe you're running the app in debug mode and unplugging the USB and connecting to the Arduino's serial. I tried that, and the app froze.

In my case, I wanted to read a double, and I did it like this:

setState(() {
        List<int> asciiValues = List<int>.from(event);
        String receivedString = String.fromCharCodes(asciiValues);
        double receivedDouble = double.tryParse(receivedString) ?? 0.0;
        msg = receivedDouble.toString();
      });

**Comment by farellsujanto** [comment]
Sorry for the very late reply, if you are using debug mode I suggest you to do wireless debugging so that your device's USB port could be utilized by the microcontroller. You cant do things like plug & unplug the phone from your PC / arduino, it won't work most of the time.
