### ISSUE TITLE
Attempt to invoke virtual method 'int android.hardware.usb.UsbDeviceConnection.controlTransfer on press connect button in example

### ISSUE THREAD

**Issue by devopsflutter** [farellsujanto/flutter_serial_communication#9]
E/MethodChannel#flutter_serial_communication( 2711): Failed to handle method call
E/MethodChannel#flutter_serial_communication( 2711): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.usb.UsbDeviceConnection.controlTransfer(int, int, int, int, byte[], int, int)' on a null object reference
E/MethodChannel#flutter_serial_communication( 2711): 	at com.hoho.android.usbserial.driver.ProlificSerialDriver$ProlificSerialPort.inControlTransfer(ProlificSerialDriver.java:139)
E/MethodChannel#flutter_serial_communication( 2711): 	at com.hoho.android.usbserial.driver.ProlificSerialDriver$ProlificSerialPort.vendorIn(ProlificSerialDriver.java:156)
E/MethodChannel#flutter_serial_communication( 2711): 	at com.hoho.android.usbserial.driver.ProlificSerialDriver$ProlificSerialPort.getStatus(ProlificSerialDriver.java:238)
E/MethodChannel#flutter_serial_communication( 2711): 	at com.hoho.android.usbserial.driver.ProlificSerialDriver$ProlificSerialPort.getControlLines(ProlificSerialDriver.java:531)
E/MethodChannel#flutter_serial_communication( 2711): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.openPort(FlutterSerialCommunicationPlugin.java:245)
E/MethodChannel#flutter_serial_communication( 2711): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.connect(FlutterSerialCommunicationPlugin.java:238)
E/MethodChannel#flutter_serial_communication( 2711): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.onMethodCall(FlutterSerialCommunicationPlugin.java:100)
E/MethodChannel#flutter_serial_communication( 2711): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#flutter_serial_communication( 2711): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_serial_communication( 2711): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter_serial_communication( 2711): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter_serial_communication( 2711): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter_serial_communication( 2711): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_serial_communication( 2711): 	at android.os.Looper.loop(Looper.java:223)
E/MethodChannel#flutter_serial_communication( 2711): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/MethodChannel#flutter_serial_communication( 2711): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_serial_communication( 2711): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter_serial_communication( 2711): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 2711): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int android.hardware.usb.UsbDeviceConnection.controlTransfer(int, int, int, int, byte[], int, int)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.usb.UsbDeviceConnection.controlTransfer(int, int, int, int, byte[], int, int)' on a null object reference
E/flutter ( 2711): 	at com.hoho.android.usbserial.driver.ProlificSerialDriver$ProlificSerialPort.inControlTransfer(ProlificSerialDriver.java:139)
E/flutter ( 2711): 	at com.hoho.android.usbserial.driver.ProlificSerialDriver$ProlificSerialPort.vendorIn(ProlificSerialDriver.java:156)
E/flutter ( 2711): 	at com.hoho.android.usbserial.driver.ProlificSerialDriver$ProlificSerialPort.getStatus(ProlificSerialDriver.java:238)
E/flutter ( 2711): 	at com.hoho.android.usbserial.driver.ProlificSerialDriver$ProlificSerialPort.getControlLines(ProlificSerialDriver.java:531)
E/flutter ( 2711): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.openPort(FlutterSerialCommunicationPlugin.java:245)
E/flutter ( 2711): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.connect(FlutterSerialCommunicationPlugin.java:238)
E/flutter ( 2711): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.onMethodCall(FlutterSerialCommunicationPlugin.java:100)
E/flutter ( 2711): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter ( 2711): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 2711): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 2711): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 2711): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 2711): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 2711): 	at android.os.Looper.loop(Looper.java:223)
E/flutter ( 2711): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/flutter ( 2711): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 2711): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 2711): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 2711): )
E/flutter ( 2711): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 2711): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 2711): <asynchronous suspension>
E/flutter ( 2711): #2      MethodChannelFlutterSerialCommunication.connect (package:flutter_serial_communication/flutter_serial_communication_method_channel.dart:51:9)
E/flutter ( 2711): <asynchronous suspension>
E/flutter ( 2711): #3      _MyAppState._connectButtonPressed (package:flutter_serial_communication_example/main.dart:54:9)

**Comment by Huangshier** [comment]
#11 
Sorry, you have also encountered this similar issue. I did not carefully review the existing questions before asking.

**Comment by farellsujanto** [comment]
Hi, sorry for the very late reply, I've updated the library to [v0.2.5](https://github.com/farellsujanto/flutter_serial_communication/releases/tag/v0.2.5) that has this fix. Please re-open the issue if its happening again.
